dist: xenial
language: cpp
compiler: clang
before_script:
- sudo apt update
- sudo apt install libgtest-dev -y
- sudo apt install cmake
- cd /usr/src/gtest
- sudo cmake .
- sudo make
- sudo cp *.a /usr/lib
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T hello_world-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uteletajp:$BINTRAY_API_KEY "https://api.bintray.com/content/teletajp/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
